language: cpp
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3

addons:
  apt:
    packages: ['portaudio19-dev', 'libfftw3-dev', 'libasound2-dev', 'libjack-dev']

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - COVERAGE
        - DOXYGEN
    - os: linux
      compiler: clang
    #- os: osx
    #  compiler: gcc
    #- os: osx
    #  compiler: clang

script:
  - ./config/script.sh



